baseURL = 'https://yaprax.ir'
languageCode = 'fa'
title = "کتابفروشی قلم من"



[pagination]
pagerSize = 6

[params]
    dateFormat = 'jan 2, 2006'


[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"
